### PR TITLE
feat(row): add possibility to disable drawing tasks for specific rows

### PR DESCRIPTION
**Pull request by Cerzus**
Disable drawing of tasks for specific rows when a 'drawTask' property
exists in the row data with a value of false or an object containing a
property 'enabled' with value false.

### CODE REVIEW

**Comment by Toilal** [comment]
Thanks ! Instead of `drawTask`, I would prefer `drawtask`. And for consistency whith others plugins, it should also works with an object : `drawtask: {enabled: false}`.

 Could you update the docs too ?

**Comment by Cerzus** [comment]
You're welcome! I didn't know which to choose because the directive is called gantt-draw-task, so I figured it would be two words, but sure, you're the boss ;)
Where should I update the docs? I've been looking for documentation about similar behaviour for the sortable and movable plugins, but could not find it anywhere...

**Comment by Cerzus** [comment]
Now that I think about it, should I also make the other attributes (moveThreshold and taskModelFactory) able to be overwritten for specific rows?

**Comment by Toilal** [comment]
`drawtask` is the name of the angularJS module `gantt.drawtask`. Other plugin related keys to override options in row/task model use the same naming logic, so it's only to try to keep it consistent through all plugins :)

Go for moveThreshold and taskModelFactory overriding too :)

Thank you again for your contributions !

**Comment by Toilal** [comment]
What's important is that `drawtask: false` is only a shortcut for `drawtask: {enabled: false}`, so for other options it will go in this configuration object.

**Comment by Toilal** [comment]
There an example also here : https://github.com/angular-gantt/angular-gantt/blob/master/src/plugins/movable.js#L98-L121.

Also the `enabled` parameter can also be a function with mouse event as first parameter, and Row object as second parameter.

**Comment by Cerzus** [comment]
I can't get taskModelFactory to work. If I add a `drawtask` property to a row in the data like this `drawtask: {moveThreshold: 50, taskModelFactory: 'hi'}`, then inside the directive `row.model` has both properties `moveThreshold` and `taskModelFactory` defined, but if I actually set `taskModelFactory` to be a function like this `drawtask: {taskModelFactory: function() {return {color: 'red'};}}`, it does not get set in `row.model`. I can't figure out why not. Any idea?

**Comment by Cerzus** [comment]
Toilal, do you have any idea about the issue in my previous comment?

**Comment by Toilal** [comment]
I'm sorry @Cerzus, I didn't investigate your problem becaus i lack of free time.

**Comment by Toilal** [comment]
taskFactory is "removed" from the row model after 1st draw... Still don't know why, but maybe it's a clone() that doesn't clone the function ...

**Comment by Toilal** [comment]
Problem is due to the demo. To showcase the 2 way databinding, It converts the model to JSON, and read JSON to reload model (at the bottom of the App, Row and Task of selected models ...). In the operation, any function from the initial model is dropped.

**Comment by Toilal** [comment]
It's fixed in master. Sorry I didn't merge directly you work, but it really helps ! thanks.

**Comment by Cerzus** [comment]
Ahh, I was hoping to become a Contributor (that happens when a pull request gets accepted, right?), but I'm happy to have helped, thank you too!

**Pull request closed without merging**
