### PR TITLE
[WIP] Webpack and TypeScript refactoring

### PR DESCRIPTION
**Pull request by Toilal**
Work in progress for #732

- [x] Add Webpack && Typescript configuration
- [x] Refactor JS files to TS files
- [x] Fix unit tests bootstrap
- [x] Make all unit tests pass
- [x] Bring back `bower.json`
- [x] Demo app should be available through rawgit
- [x] Make scripts build both minified and non-minified assets
- [x] Fix sortable plugin
- [x] Add comments header to distribution files
- [x] Update contributing docs with new workflow
- [ ] ~~Use classes as much as possible~~
- [ ] ~~Add types on every variable~~
- [ ] ~~Add hot module reload~~

To test this branch, run `yarn dev` (or `npm run dev`).

http://rawgit.com/angular-gantt/angular-gantt/2.0.x/demo.dist/index.html

### CODE REVIEW

**Comment by Toilal** [comment]
Hey @Schweigi ! Could you give this branch a test on the demo app ?

**Comment by Toilal** [comment]
Demo app available at http://rawgit.com/angular-gantt/angular-gantt/2.0.x/demo/dist/index.html

**Comment by Schweigi** [comment]
@Toilal will test the demo app. nice work!

**Comment by Schweigi** [comment]
@Toilal Tested each feature of the Demo app. It works great. There are two small issues regarding custom sorting of sub-rows in the tree view and "disabling dependencies" still shows the dependency endpoints when hovering with the mouse over a task - but I think both issues are unrelated to your Demo changes.

**Comment by Schweigi** [comment]
Btw. used Safari (10.1)

**Comment by Toilal** [comment]
Thanks for running some tests @Schweigi. It seems both issue you've noticed are also here on master branch.

**Comment by jcsalberto** [comment]
Hi, can you release the version for Angular 2?

thank you very much

**Comment by Toilal** [comment]
It's not planned, unless you want to pay for this.

**Comment by laserus** [comment]
@Toilal what do you mean by 'it is not planned'? Is the the whole point of this WIP is to transfer codebase from AngularJs to Angular?

**Comment by Toilal** [comment]
This pull request is written to provide a TypeScript/Webpack based version of angular-gantt, but it's still written for AngularJS and heavily relies on AngularJS API (directives, $templatecache, $scope ...)

Of course, it's a good step to go for Angular, but there's still much work to really perform the migration.

I'm currently working with VueJS on some projects, and don't use Angular at all, so there's more chance to see a port of this component to VueJS than to Angular.

There's so much things that are written the AngularJS way in this project and that may cause issues in younger frameworks (Vue, React, Angular ...), that I think I need to rewrite many parts from scratch to handle them. 

It would be great to implement this module for multiple frameworks, including Angular, but i'm not sure i'll be able to share much code between frameworks implementations. And I don't have much spare time to support everything, so I think i'll focus on VueJS

But I'm still opened for contribution to migrate in the other frameworks.

**Comment by laserus** [comment]
@Toilal Thanks, now I understand. 

I was really confused by webpack and typescript in the name to such a point that I was thinking that this PR is about upgrading to angular 2/4. Judging from the code there are 5k lines of src/core and 10k lines of 'src'... quite large to migrate.

**Comment by Toilal** [comment]
It's now the default develop branch.

**Pull request merged**
