### PR TITLE
fix(tasks): Fire event task move when a task is moved quickly

### LINKED ISSUE #190: Event 'onTaskUpdated' not fired
Sometimes, the on-task-updated event is not fired when i move a task. But on resize everything's OK.

I use the latest stable version (0.6.4)

Is this a known bug or maybe it's already fix on the master...?

### PR DESCRIPTION
**Pull request by aelamrani**
resolve #190

### CODE REVIEW

**Comment by Toilal** [comment]
Thanks, but this branch is not maintained anymore. And changes must be done in source files.

**Comment by aelamrani** [comment]
Ok, this fix could help someones who have this version on production.. 

I didn't try to reproduce it on new versions, but i won't be surprise to...

**Comment by Toilal** [comment]
I'll try to merge in `master` and `1.1.x` if code is still the same.

**Comment by Toilal** [comment]
in master, it has been refactored. I don't think it can be reproduced in current version, but please give it a try if you have some time ...

If you really want this to be merged in 0.7.x branch, I would allow it but please make changes in sources and run the build with grunt to generate assets files.

**Comment by aelamrani** [comment]
I found the same code here : 
<code>angular-gantt-plugins.js:635</code>
<code>angular-gantt-movable-plugin.js:353</code>

Ok i will try it on master ASAP... But i can see the events mechanism changed a lot... So maybe the event is now fired on master...

Is anybody can reproduce this bug on any version?

**Comment by Schweigi** [comment]
I think on master it should have been fixed with 9cf963a0a005507d0fdfd765a03abbb636281921.

**Comment by aelamrani** [comment]
I'm not sure because this fix exists since v0.7.x and i reproduced it this morning on this version...

**Pull request closed without merging**
