### PR TITLE
Fix priority

### PR DESCRIPTION
**Pull request by p3nt4**
I found that this was required for priorities to be updated properly.

### CODE REVIEW

**Comment by p3nt4** [comment]
This fix is actually not sufficient. I added this line above to ensure priorities were computed correctly, but now tooltips appear under tasks with specific priorities.

image

**Comment by Toilal** [comment]
I can remember this issue, and didn't found any better solution than the actual codebase. I let this one open for now in case you find a proper solution later.

**Comment by p3nt4** [comment]
Thanks for the reply. 
What is weird is that priorities worked fine in version 1.2.8. Updating to 1.3.2 is what broke it for me.
Is there a different way to use it in this version?

**Comment by Toilal** [comment]
It would help if you can identify the exact commit that breaks the feature. (you could use [git bisect](https://git-scm.com/docs/git-bisect))

**Comment by p3nt4** [comment]
I removed the z-index attribute in the task css. It seems to work fine now.

**Comment by Toilal** [comment]
Merged manually, thanks !

**Pull request closed without merging**
