### PR TITLE
feat(groups): Add promote display mode

### PR DESCRIPTION
**Pull request by renekorss**
I know that it can be achieved with simple template override for `GanttGroupController`, but then there is no opportunity to have both. This works well for me.

### CODE REVIEW

**Comment by Toilal** [comment]
Hi @renekorss, thanks for this PR.

Could you rebase on current master, and make the feature in a single commit ?

**Comment by Toilal** [comment]
I'll add this in docs.

**Comment by Toilal** [comment]
Ho, I just saw it's already done ! Thanks, perfect PR :)

**Comment by renekorss** [comment]
Thanks @Toilal for merging. I learned a lot about Git! Thanks again!

**Pull request merged**
